// src/controllers/sessionController.js
// ─────────────────────────────────────────────────────
// Handles all session business logic:
//   createSession   → mentor only
//   joinSession     → student only, via invite code
//   startSession    → mentor only, changes status to active
//   endSession      → mentor only, changes status to ended
//   getMySession    → mentor gets their active session
//   getSessionByCode→ student looks up session before joining
// ─────────────────────────────────────────────────────

const {supabaseAdmin} = require('../config/supabase')

// ── createSession ─────────────────────────────────────
// Only mentors can call this.
// Creates a session row — invite_code is auto-generated by DB.
// Returns the full session including the invite link.
// ─────────────────────────────────────────────────────
async function createSession(req, res) {
  try {
    const { title, description } = req.body
    const mentor_id = req.user.id

    if (!title || !title.trim()) {
      return res.status(400).json({ error: 'Session title is required' })
    }

    const { data: session, error } = await supabaseAdmin
      .from('sessions')
      .insert({
        title: title.trim(),
        description: description?.trim() || '',
        mentor_id,
        status: 'waiting'
      })
      .select()
      .single()

    if (error) {
      return res.status(400).json({ error: error.message })
    }

    res.status(201).json({
      message: 'Session created successfully',
      session,
      invite_link: `${process.env.CLIENT_URL}/join/${session.invite_code}`
    })
  } catch (err) {
    console.error('[createSession]', err.message)
    res.status(500).json({ error: 'Failed to create session' })
  }
}

// ── joinSession ───────────────────────────────────────
// Only students can call this.
// Looks up the session by invite_code from the URL param.
// Adds the student to session_participants table.
// Returns session info so the student can enter the editor.
// ─────────────────────────────────────────────────────
async function getSessionById(req, res) {
  try {
    const { id } = req.params

    const { data: session, error } = await supabaseAdmin
      .from('sessions')
      .select('*')
      .eq('id', id)
      .maybeSingle()

    if (error || !session) {
      return res.status(404).json({ error: 'Session not found' })
    }

    res.json(session)
  } catch (err) {
    console.error(err)
    res.status(500).json({ error: 'Server error' })
  }
}

async function joinSession(req, res) {
  console.log("join session hit");
  try {
    const { invite_code } = req.params
    const student_id = req.user.id

    console.log("invite_code from url",invite_code);
    

    // Find session by invite code
    const { data: session, error: sessionError } = await supabaseAdmin
      .from('sessions')
      .select('*, profiles!sessions_mentor_id_fkey(full_name)')
      .eq('invite_code', invite_code)
      .maybeSingle()

      console.log("invite code:" , invite_code);
      console.log("session found", session);
      console.log("session error", sessionError);
      
      

    if (sessionError || !session) {
      return res.status(404).json({ error: 'Session not found. Check your invite link.' })
    }

    // Don't allow joining ended sessions
    if (session.status === 'ended') {
      return res.status(400).json({ error: 'This session has ended.' })
    }

    // Don't allow mentor to join their own session as student
    if (session.mentor_id === student_id) {
      return res.status(400).json({ error: 'You are the mentor of this session.' })
    }

    // Add student to participants (upsert avoids duplicate error on rejoin)
    const { error: joinError } = await supabaseAdmin
      .from('session_participants')
      .upsert({ session_id: session.id, user_id: student_id })

    if (joinError) {
      return res.status(400).json({ error: joinError.message })
    }
    
     
    res.json({
      message: 'Joined session successfully',
      session
    })
    
    
     console.log("join user:" , req.user);
  } catch (err) {
    console.error('[joinSession]', err.message)
    res.status(500).json({ error: 'Failed to join session' })
  }
}

// ── startSession ──────────────────────────────────────
// Mentor changes session status from 'waiting' → 'active'.
// Records started_at timestamp.
// Emits a socket event so students are notified instantly.
// ─────────────────────────────────────────────────────
async function startSession(req, res) {
  try {
    const { session_id } = req.params
    const mentor_id = req.user.id

    // Verify this mentor owns this session
    const { data: existing } = await supabaseAdmin
      .from('sessions')
      .select('id, status, mentor_id')
      .eq('id', session_id)
      .single()

    if (!existing) {
      return res.status(404).json({ error: 'Session not found' })
    }

    if (existing.mentor_id !== mentor_id) {
      return res.status(403).json({ error: 'You do not own this session' })
    }

    if (existing.status === 'active') {
      return res.status(400).json({ error: 'Session is already active' })
    }

    if (existing.status === 'ended') {
      return res.status(400).json({ error: 'Session has already ended' })
    }

    const { data: session, error } = await supabaseAdmin
      .from('sessions')
      .update({ status: 'active', started_at: new Date().toISOString() })
      .eq('id', session_id)
      .select()
      .single()

    if (error) return res.status(400).json({ error: error.message })

    // Notify all sockets in this session room
    // io is attached to app in index.js
    const io = req.app.get('io')
    io.to(session_id).emit('session:started', { session })

    res.json({ message: 'Session started', session })
  } catch (err) {
    console.error('[startSession]', err.message)
    res.status(500).json({ error: 'Failed to start session' })
  }
}

// ── endSession ────────────────────────────────────────
// Mentor changes session status to 'ended'.
// Records ended_at timestamp.
// Notifies all connected sockets.
// ─────────────────────────────────────────────────────
async function endSession(req, res) {
  try {
    const { session_id } = req.params
    const mentor_id = req.user.id

    const { data: existing } = await supabaseAdmin
      .from('sessions')
      .select('id, status, mentor_id')
      .eq('id', session_id)
      .single()

    if (!existing) {
      return res.status(404).json({ error: 'Session not found' })
    }

    if (existing.mentor_id !== mentor_id) {
      return res.status(403).json({ error: 'You do not own this session' })
    }

    if (existing.status === 'ended') {
      return res.status(400).json({ error: 'Session is already ended' })
    }

    const { data: session, error } = await supabaseAdmin
      .from('sessions')
      .update({ status: 'ended', ended_at: new Date().toISOString() })
      .eq('id', session_id)
      .select()
      .single()

    if (error) return res.status(400).json({ error: error.message })

    // Notify all sockets and disconnect them from the room
    const io = req.app.get('io')
    io.to(session_id).emit('session:ended', { session })

    res.json({ message: 'Session ended', session })
  } catch (err) {
    console.error('[endSession]', err.message)
    res.status(500).json({ error: 'Failed to end session' })
  }
}

// ── getMySessions ─────────────────────────────────────
// Returns all sessions created by the logged-in mentor.
// Includes participant count for each session.
// ─────────────────────────────────────────────────────
async function getMySessions(req, res) {
  try {
    const mentor_id = req.user.id

    const { data: sessions, error } = await supabaseAdmin
      .from('sessions')
      .select('*, session_participants(count)')
      .eq('mentor_id', mentor_id)
      .order('created_at', { ascending: false })

    if (error) return res.status(400).json({ error: error.message })

    res.json({ sessions })
  } catch (err) {
    console.error('[getMySessions]', err.message)
    res.status(500).json({ error: 'Failed to fetch sessions' })
  }
}

// ── getSessionByCode ──────────────────────────────────
// Public-ish — used by student to preview session before joining.
// Called when student lands on /join/:invite_code page.
// ─────────────────────────────────────────────────────
async function getSessionByCode(req, res) {
  try {
    const { invite_code } = req.params

    const { data: session, error } = await supabaseAdmin
      .from('sessions')
      .select('id, title, description, status, invite_code, profiles!sessions_mentor_id_fkey(full_name)')
      .eq('invite_code', invite_code)
      .single()

    if (error || !session) {
      return res.status(404).json({ error: 'Session not found' })
    }

    res.json({ session })
  } catch (err) {
    console.error('[getSessionByCode]', err.message)
    res.status(500).json({ error: 'Failed to fetch session' })
  }
}

async function getSessionById(req, res) {
  try {
    const { id } = req.params

    const { data: session, error } = await supabaseAdmin
      .from('sessions')
      .select('*')
      .eq('id', id)
      .maybeSingle()

    if (error || !session) {
      return res.status(404).json({ error: 'Session not found' })
    }

    res.json(session)
  } catch (err) {
    console.error(err)
    res.status(500).json({ error: 'Server error' })
  }
} 


module.exports = {
  createSession,
  joinSession,
  startSession,
  endSession,
  getMySessions,
  getSessionByCode,
  getSessionById
}
